### PR TITLE
arm64: dts: marvell: ESPRESSObin: add second UART port

### PR DESCRIPTION
**Pull request by 1082008**
Add a node in Armada 3720 ESPRESSObin DTS file for the second UART.

Signed-off-by: László ÁSHIN <laszlo@ashin.hu>

### CODE REVIEW

**Comment by 1082008** [comment]
UART on P9 pin 24, 26 works with this configuration on ESPRESSObin v5.0.1 board properly.

According to http://wiki.espressobin.net/tiki-download_file.php?fileId=123&display there is an UART4 on P9 pin 11, 13 but I haven't figured out how to drive it. Do you have any idea?

**Comment by miquelraynal** [comment]
Hello László,

I am sorry I could not get UART2 properly working on ESPRESSObin. Did you select a special hw configuration with the jumpers ? I am using a v3.1.1 board, not a 5.0.1 like you. By any chance, would you have an older revision to see if it still works?

Indeed the image you refer to shows a UART4 pair of pins on J17 header, but their signal name is "NC" (Not Connected). Plus, AFAIK, the A3700 SoC that is on the ESPRESSObin only has two UART ports. I don't think you can have a third one natively.

Thank you,
Miquèl

**Comment by gclement** [comment]
If you have a look on the page 4 of
http://espressobin.net/wp-content/uploads/2017/08/ESPRESSObin_V5_Schematics.pdf

We see that the pins 11 and 13 are not connected at all, so I think
there is a mistake in that image.

And I confirm that the Armada 3720 Soc has only 2 UART ports.

Gregory

**Comment by gclement** [comment]
On jeu., oct. 05 2017, Miquèl Raynal <notifications@github.com> wrote:

> Hello László,
>
> I am sorry I could not get UART2 properly working on ESPRESSObin. Did
> you select a special hw configuration with the jumpers ? I am using a
> v3.1.1 board, not a 5.0.1 like you. By any chance, would you have an
> older revision to see if it still works?
>
> Indeed the image you refer to shows a UART4 pair of pins on J17
> header, but their signal name is "NC" (Not Connected). Plus, AFAIK,
> the A3700 SoC that is on the ESPRESSObin only has two UART ports. I
> don't think you can have a third one natively.
>
> Thank you,
> Miquèl

If you have a look on the page 4 of
http://espressobin.net/wp-content/uploads/2017/08/ESPRESSObin_V5_Schematics.pdf

We see that the pins 11 and 13 are not connected at all, so I think
there is a mistake in that image.

And I confirm that the Armada 3720 Soc has only 2 UART ports.

Gregory

>
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/MISL-EBU-System-SW/mainline-public/pull/79#issuecomment-334479383

-- 
Gregory Clement, Free Electrons
Kernel, drivers, real-time and embedded Linux
development, consulting, training and support.
http://free-electrons.com

**Comment by 1082008** [comment]
@gclement thanks, then I wont try to make more than 2 uarts work on this board :)

@miquelraynal I didn't make any jumper changes, just connected a CH340G USB serial adapter to the pins via a level shifter circuit (1.8V-3.3V conversion). But this second UART doesn't seem to be stable because if I connect an arduino pro mini to it then it fails to reprogram the MCU flash through the UART. So the situation needs to be investigated further. I will definitely check it after applying the changes you mentioned on #78 . I will get back to my board in 3 hours and report the results.

Thanks!

**Comment by 1082008** [comment]
I have just tested espressobin with CH340G and the level converter.
I think espressobin misses some bytes on its RX line. TX seems to be OK. espressobin is very sensitive to the voltage level and I haven't figured out the proper setting. If you have access to the datasheet please help me out. What is the maximal voltage armada 3720 takes as logic low on the UA2_RX pin? What is the maximal tolerated voltage on that pin?

I ran the test with `minicom -b 2400 -D /dev/tty[MV1/USB0] -w` on espressobin/my laptop respectively, and typed some characters. My laptop received everything properly but espressobin got just garbage.

**Comment by miquelraynal** [comment]
@Kodest My bad, I checked with a 5V TTL USB converter, of course there was nothing on the console.

I used a 3.3V USB converter and it worked well in both directions, I tried 9600b and 2400b. I guess your level converter is faulty. But if you probe with an oscilloscope, the noise level on the ESPRESSObin TX line is abnormally high.

As the pins on the header are dedicated for GPIO, I will not add the UART2 node but simply a comment in the device tree to suggest copying the node from the 3720-db DTS if needed.

Thank you,
Miquèl

**Comment by 1082008** [comment]
Have you connected your 3.3V USB converter directly to the RX/TX pins of the espressobin without a level converter? I assumed that a 3.3V -> 1.8V conversion is needed because armada 3720 uses 1.8 GPIO voltage. I was afraid that 3.3V could harm the chip. (Unfortunatelly I have no access to the datasheet.)

**Comment by miquelraynal** [comment]
I don't think the pins would be harmed using 3.3V. For me the problem is more what is the minimum input level for the USB converter to detect a logical '1'. The datasheet states the output value will be 1.8V +/-0.1V but I did not see the maximum supported incoming power anywhere. Usually this value is high enough to not break anything when using the incorrect input level (I first tried with 5V converter) as long as there is not so much current involved. Of course it is always better to use the correct voltages.

Converting noisy 1.8V signal to 5V, if the the converter is not so good, could produce your errors. The best would be to try with a native 1.8V TTL to USB serial converter.

**Comment by 1082008** [comment]
I wrote a [very simple terminal emulator](https://github.com/Kodest/avrcryptodev/blob/master/ser.c) and I proved that UART2 RX and TX lines are both working properly - the voltage levels are correct now with the setup I use. Thanks for your help!

**Pull request closed without merging**
